# Generated by Django 2.1.7 on 2025-12-02 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('document_type', models.CharField(default='Unknown', max_length=50)),
                ('file_path', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('ai_verification_status', models.CharField(default='Pending', max_length=20)),
                ('ai_confidence_score', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'document_submissions',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=50)),
                ('course_year', models.CharField(max_length=20)),
                ('paying_dept', models.CharField(max_length=50)),
                ('amount', models.FloatField()),
                ('payment_date', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'payments',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('contact', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('course', models.CharField(max_length=50)),
                ('course_year', models.CharField(max_length=20)),
                ('library_fee', models.FloatField(default=0.0)),
                ('hostel_fee', models.FloatField(default=0.0)),
                ('tution_fee', models.FloatField(default=0.0)),
                ('exam_fee', models.FloatField(default=0.0)),
                ('lab_hod_fee', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
