# Generated by Django 2.1.7 on 2025-12-02 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NoDueApp', '0003_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('student_id', 'course_year')},
        ),
    ]
