from django.urls import path

from . import views

urlpatterns = [path("index.html", views.index, name="index"),
               path("", views.index, name="index_root"),
               path("AdminLogin.html", views.AdminLogin, name="AdminLogin"),	      
               path("AdminLoginAction", views.AdminLoginAction, name="AdminLoginAction"),
               path("AdminScreen.html", views.AdminScreen, name="AdminScreen"),
               path("AddEmployeeAction", views.AddEmployeeAction, name="AddEmployeeAction"),
               path("AddEmployee.html", views.AddEmployee, name="AddEmployee"),
               path("AddStudentAction", views.AddStudentAction, name="AddStudentAction"),
               path("AddStudent.html", views.AddStudent, name="AddStudent"),
	       path("StudentLogin.html", views.StudentLogin, name="StudentLogin"),
	       path("StudentLoginAction", views.StudentLoginAction, name="StudentLoginAction"),
	       path("StudentScreen.html", views.StudentScreen, name="StudentScreen"),
	       path("EmployeeLogin.html", views.EmployeeLogin, name="EmployeeLogin"),
               path("EmployeeLoginAction", views.EmployeeLoginAction, name="EmployeeLoginAction"),
               path("EmployeeScreen.html", views.EmployeeScreen, name="EmployeeScreen"),
	       path("ViewEmployees", views.ViewEmployees, name="ViewEmployees"),
               path("ViewEmployees.html", views.ViewEmployees, name="ViewEmployees"),
               path("UpdateEmployeeForm", views.UpdateEmployeeForm, name="UpdateEmployeeForm"),
               path("UpdateEmployeeAction", views.UpdateEmployeeAction, name="UpdateEmployeeAction"),
               path("DeleteEmployeeAction", views.DeleteEmployeeAction, name="DeleteEmployeeAction"),
               path("ViewPayments", views.ViewPayments, name="ViewPayments"),
               path("ViewPayments.html", views.ViewPayments, name="ViewPayments"),
	       path("ViewPaymentAction", views.ViewPaymentAction, name="ViewPaymentAction"),
	       path("UpdateFee", views.UpdateFee, name="UpdateFee"),
               path("UpdateFee.html", views.UpdateFee, name="UpdateFee"),
	       path("UpdateFeeAction", views.UpdateFeeAction, name="UpdateFeeAction"),
	       path("AcceptFee.html", views.AcceptFee, name="AcceptFee"),
	       path("AcceptFeeAction", views.AcceptFeeAction, name="AcceptFeeAction"),	       
	       path("ViewStudents", views.ViewStudents, name="ViewStudents"),
               path("ViewStudents.html", views.ViewStudents, name="ViewStudents"),
               path("UpdateStudentForm", views.UpdateStudentForm, name="UpdateStudentForm"),
               path("UpdateStudentAction", views.UpdateStudentAction, name="UpdateStudentAction"),
               path("DeleteStudentAction", views.DeleteStudentAction, name="DeleteStudentAction"),
	       path("GenerateNoDue.html", views.GenerateNoDue, name="GenerateNoDue"),
	       path("GenerateNoDueAction", views.GenerateNoDueAction, name="GenerateNoDueAction"),	
	       path("Download", views.Download, name="Download"),
	       path("ScanQR.html", views.ScanQR, name="ScanQR"),
	       path("VerifyCertificate", views.VerifyCertificate, name="VerifyCertificate"),
	       path("DownloadByQR", views.DownloadByQR, name="DownloadByQR"),	
]
